### ISSUE TITLE
NoClassDefFoundError for v3.9.0 

### ISSUE THREAD

**Issue by msymons** [jenkinsci/cucumber-reports-plugin#170]
The following error was seen after updating Cucumber Reports Plugin from 3.8.0 to v3.9.0.  But only one one of our Jenkins servers.

```
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] JSON report directory is "xxx/target/cucumber"
[CucumberReport] Copied 155 json files from workspace "/var/lib/jenkins/jobs/xxx Nightly/workspace/xxxx/target/cucumber" to reports directory "/var/lib/jenkins/jobs/xxx/builds/268/cucumber-html-reports/.cache"
[CucumberReport] Processing 155 json files:
[CucumberReport] /var/lib/jenkins/jobs/xxx Nightly/builds/268/cucumber-html-reports/.cache/xxxxxxxxxx/cucumber.json
...
ERROR: Step ‘Cucumber reports’ aborted due to exception: 
java.lang.NoClassDefFoundError: Could not initialize class net.masterthought.cucumber.ReportBuilder
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:268)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:207)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
```

Rolling back to v3.8.0 fixed the problem. 

I then examined recent commits for cucumber-reports and see that v3.9.0 introduced support for pipelines via #139.  

Whilst our Jenkins server with the NoClassDefFoundError  does not use Pipelines I then went ahead and updated Cucumber Reports back to v3.9.0 again - and **also** updated other plugins (see screenshot).

![cucumber-noclassdeffounderror](https://user-images.githubusercontent.com/4938718/29169474-212cb6fa-7dcc-11e7-8e9b-620b1902caef.png)

No more NoClassDefFoundError!  Cucumber Reports Plugin v3.9.0 now worked perfectly.

So,, would I be right in thinking that the plugin has a dependency that is not tested for on upgrade?  The only [documented](https://plugins.jenkins.io/cucumber-reports) dependencies that I could find are for Structs Plugin v.1.8  and Token Macro Plugin v.2.0

I would also suggest that the "releases" page for the plugin needs to provide a summary of important changes.  Sure, the README.md mentions pipelines...  but does not say anything about when this was introduced.

**Comment by damianszczepanik** [comment]
Hmm, interesting. Your analyze makes sense except the practice I did. I've installed clean Jenkins with only cucumber-reports Plugin and following dependencies were added:
```

bouncycastle API Plugin 
Structs Plugin 
Token Macro Plugin 
Cucumber reports
```

I didn't have Pieplie and did not use it as well bu the report was generated smoothly. Then I don't think this is direct dependency with Pipeline...

**Comment by msymons** [comment]
So could the problem be with with Structs plugin?  The docs say that the dependency is on v1.8 of that plugin.  As you can see from the screenshot, I was running Structs Plugin v1.9 when experiencing the NoClassDefFoundError.  This should have been OK.

Again, from the screenshot, Structs Plugin was one of the plugins that was updated.  In this case, to v1.10.
And, per my original description, after the upgrade, Cucumber Reports worked fine again.

Maybe the dependency is really on Structs Plugin v1.10?

**Comment by msymons** [comment]
@damianszczepanik,  I have investigated a bit more.  I have more than one Jenkins server and found one (also Jenkins v2.46.2) that had Cucumber Reports plugin updated to v3.9.0 when it was first released a month ago and running the "official required versions" of plugin dependencies (but not the latest versions) and was producing good reports with no errors.

This would not have been the case if there was a dependency on (say) the latest version of stucts.  Thus, there is doubtless no dependency problem.

Bearing in mind that upgrading (or rolling-back) plugins involves a restart of Jenkins, is it not likely that NoClassDefFoundError was caused by Cucumber report Plugin v3.9.0 having failed to start properly on the one Jenkins server?  And it started fine when rolling back to v3.8.0 and also started fine when upgrading back to v3.9.0 again?

**Comment by damianszczepanik** [comment]
Strange, will try to look at this...

**Comment by YugandharBandari** [comment]
i faced thsi error in 3.11 version but its fixed when i enter correct path for json file

**Comment by damianszczepanik** [comment]
What do you mean by correct path?
